### ISSUE TITLE
Request blocked by Auth Cosmos DB

### ISSUE THREAD

**Issue by philippsautter** [azure-ai-foundry/foundry-samples#397]
Hello everyone,

I have an error in the new Azure AI Foundry related to authentication with Cosmos DB.

Initially, I had an AAD connection to Cosmos DB, but I have since switched to API keys. However, I am still receiving the following error:

`Error loading your agents.Response status code does not indicate success: Forbidden (403); Substatus: 5300; ActivityId: 66f0becd-1c33-4db6-87b2-b2b5f23fd51e; Reason: (Request blocked by Auth acdb-XYZ : The given request [POST /dbs/enterprise_memory/colls] cannot be authorized by AAD token in data plane. Learn more: https://aka.ms/cosmos-native-rbac. ActivityId: 66f0becd-1c33-4db6-87b2-b2b5f23fd51e, Microsoft.Azure.Documents.Common/2.14.0, Microsoft.Azure.Cosmos.Tracing.TraceData.ClientSideRequestStatisticsTraceDatum, Linux/12 cosmos-netstandard-sdk/3.39.1); Request ID: 0e471b9c-a148-408d-801f-e8476651c130`

Here is a screenshot of the error:
<img width="1823" height="188" alt="Image" src="https://github.com/user-attachments/assets/2fea35ed-7cfa-4540-b661-ca27196320f3" />

Does anyone have any idea what could be causing this? I'm a little confused because the error says something about AAD, but I'm currently using API keys.

Thank you and best regards

**Comment by georgeollis** [comment]
Same issue for me

**Comment by Shaheer4636** [comment]
Is this issue resolved? @georgeollis

**Comment by georgeollis** [comment]
@Shaheer4636 - Id say that's resolved now

**Comment by Shaheer4636** [comment]
@georgeollis , I am still facing same issue. It is working fine in dev but not in staging env. Both have same configurations and settings.
